### ISSUE TITLE
行政号码对应错误

### ISSUE THREAD

**Issue by AileenXie** [renyijiu/id_validator#2]
身份证对应行政区域错误；
如362324，在1999年以前对应江西省上饶市铅山县，2000年发生了变化：
irb(main):002:0> IdValidator.get_info('362324***************')
=> {:address_code=>"362324", :address=>"江西省宜春地区丰城县", :abandoned=>true, 

参考解决办法：
根据出生年份查当年行政区对应号码

**Comment by jxlwqq** [comment]
确实有这个问题。

**Comment by renyijiu** [comment]
感谢反馈，问题是存在。
身份证显示的应该是办理当年的行政区域规划，按照出生年份去查找行政区域，也不一定准确。

我会考虑一下解决方案，有后续思路会继续反馈！也欢迎提供想法👏

**Comment by jxlwqq** [comment]
在原来的废弃数据中，362324对应的数据为
```php
['362324' => '丰城县']
```
如果，改为以下的格式，会不会更好一点：
```php
[
'362324' =>
        [
            [
                'address' => '丰城县',
                'start_year' => '',
                'end_year' => '1981',
            ],
            [
                'address' => '铅山县',
                'start_year' => '1982',
                'end_year' => '1999',
            ],
        ]
]
```
这样可以理清一个地址码的来龙去脉，但是由于民政部官网能提供的最早数据是1980年，所以1980年以前的变更是暂时无法知晓的。

**Comment by jxlwqq** [comment]
目前，废弃的地址码的格式为：
```
'362324' => '丰城县'
```
改成以下格式如何：
```php
'362324' =>
        [
            [
                'address' => '丰城县',
                'start_year' => '',
                'end_year' => '1981',
            ],
            [
                'address' => '铅山县',
                'start_year' => '1982',
                'end_year' => '1999',
            ],
        ],
```
这样可以理清某个地址码的来龙去脉，但是有一个问题是，民政部只提供了1980-至今的数据，1980前的数据暂不知晓。

**Comment by jxlwqq** [comment]
目前，废弃的地址码的格式为：
```
'362324' => '丰城县'
```
改成以下格式如何：
```php
'362324' =>
        [
            [
                'address' => '丰城县',
                'start_year' => '',
                'end_year' => '1981',
            ],
            [
                'address' => '铅山县',
                'start_year' => '1982',
                'end_year' => '1999',
            ],
        ],
```
这样可以理清某个地址码的来龙去脉，但是有一个问题是，民政部只提供了1980-至今的数据，1980前的数据暂不知晓。

**Comment by jxlwqq** [comment]
github升级了？这么不稳定，评论显示不出来。。。

目前，废弃的地址码的格式为：
```
'362324' => '丰城县'
```
改成以下格式如何：
```php
'362324' =>
        [
            [
                'address' => '丰城县',
                'start_year' => '',
                'end_year' => '1981',
            ],
            [
                'address' => '铅山县',
                'start_year' => '1982',
                'end_year' => '1999',
            ],
        ],
```
这样可以理清某个地址码的来龙去脉，但是有一个问题是，民政部只提供了1980-至今的数据，1980前的数据暂不知晓。

**Comment by renyijiu** [comment]
GitHub的存储系统出问题了 https://status.github.com/messages ，所以页面数据抽风。

按我的理解，1980以前的数据没有的话影响应该不大，毕竟身份证实际上的颁发也是在这之后，所以数据上应该可以的。

改成这个格式的话，我觉得可能初期原始数据处理会比较麻烦。另外我看对应的市级编码也是有变化的，那对应的查找过程其实也需要进行修改，不然数据也会出现问题。

**Comment by jxlwqq** [comment]
增加"地址码更新时间线"逻辑：https://github.com/jxlwqq/id-validator.py/commit/567b25cfb8c52325881f512d032d4f926030b24d
有时间请 review 一下，主要是将原来的废弃地址码数据改为了所有地址码的变更时间线，代码改动不是很大。

**Comment by renyijiu** [comment]
@jxlwqq 我觉的废弃地址码这样修改是可以的，我目前也只能想到这种方案，因为无法获取完全准确的信息，只能确保获取的地址是可以接受的，无法保证完全和用户身份证上显示一致。

查询时考虑从现在往以前推，获取历史数据中最近的一个作为结果。
